apiVersion: gemfire.vmware.com/v1
kind: GemFireCluster
metadata:
  name: gemfire1
spec:
  image: registry.tanzu.vmware.com/pivotal-gemfire/vmware-gemfire:9.15.1
  servers:
    replicas: 3
  locators:
    overrides:
      gemFireProperties: 
        - name: start-dev-rest-api
          value: "true"