apiVersion: v1
kind: Service
metadata:
  name: gemfire1-lb-mngt
spec:
  selector:
    gemfire.vmware.com/app: gemfire1-locator
  ports:
    - name: management
      port: 7070
      targetPort: 7070
      nodePort: 30070
  sessionAffinity: ClientIP
  sessionAffinityConfig:
      clientIP:
        timeoutSeconds: 10800
  type: LoadBalancer
  externalIPs:
  # your minikube ip -> minikube ip
  - 172.23.24.105